name: cinemapedia
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  animate_do: ^3.0.2
  card_swiper: ^3.0.1
  dio: ^5.0.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_riverpod: ^2.2.0
  go_router: ^14.1.1
  intl: ^0.19.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.3
  window_manager: ^0.3.8
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  build_runner: ^2.4.10
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true

  assets:
    - .env
